INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (1, 'http://indiatimes.com/id/sapien.xml', 'Highlights from Tampa Bay Buccaneers vs. Dallas Cowboys');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (2, 'https://auda.org.au/erat/eros/viverra/eget.js', 'Highlights from Philadelphia Eagles vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (3, 'https://digg.com/in.aspx', 'Highlights from Pittsburgh Steelers vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (4, 'http://zimbio.com/mattis/nibh/ligula/nec/sem/duis/aliquam.js', 'Highlights from Carolina Panthers vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (5, 'http://dion.ne.jp/vestibulum/ante/ipsum/primis.xml', 'Highlights from Cincinnati Bengals vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (6, 'http://over-blog.com/consequat/ut/nulla/sed/accumsan/felis.json', 'Highlights from Seattle Seahawks vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (7, 'http://exblog.jp/penatibus/et/magnis/dis/parturient/montes.jpg', 'Highlights from Arizona Cardinals vs. Tennessee Titans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (8, 'https://usda.gov/aenean/fermentum/donec/ut.js', 'Highlights from San Francisco 49ers vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (9, 'https://e-recht24.de/aliquet/ultrices/erat/tortor/sollicitudin/mi.jsp', 'Highlights from Houston Texans vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (10, 'http://exblog.jp/sit/amet/nulla/quisque.jsp', 'Highlights from Los Angeles Chargers vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (11, 'http://slashdot.org/molestie/nibh/in.png', 'Highlights from Kansas City Chiefs vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (12, 'https://columbia.edu/interdum/eu/tincidunt/in/leo/maecenas/pulvinar.json', 'Highlights from Denver Broncos vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (13, 'https://google.cn/consequat/ut/nulla/sed/accumsan.aspx', 'Highlights from New Orleans Saints vs. Green Bay Packers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (14, 'https://nymag.com/tellus/nulla/ut/erat/id/mauris/vulputate.aspx', 'Highlights from Miami Dolphins vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (15, 'http://huffingtonpost.com/in/hac/habitasse.jpg', 'Highlights from Los Angeles Rams vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (16, 'https://scientificamerican.com/rutrum/ac/lobortis/vel/dapibus.html', 'Highlights from Las Vegas Raiders vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (17, 'http://cnbc.com/sed/ante.json', 'Highlights from Washington Football Team vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (18, 'https://diigo.com/a/feugiat/et.json', 'Highlights from Buffalo Bills vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (19, 'http://ezinearticles.com/vivamus/vel/nulla/eget/eros/elementum.aspx', 'Highlights from Carolina Panthers vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (20, 'http://simplemachines.org/id.png', 'Highlights from Chicago Bears vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (21, 'http://hatena.ne.jp/luctus/et/ultrices.png', 'Highlights from Cleveland Browns vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (22, 'http://lycos.com/ut/erat/id/mauris/vulputate/elementum.jpg', 'Highlights from Los Angeles Rams vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (23, 'https://mozilla.com/dictumst.xml', 'Highlights from Denver Broncos vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (24, 'https://printfriendly.com/eget/vulputate/ut.png', 'Highlights from New England Patriots vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (25, 'https://shop-pro.jp/rhoncus/dui/vel/sem/sed.jsp', 'Highlights from San Francisco 49ers vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (26, 'http://whitehouse.gov/cras/in/purus/eu.aspx', 'Highlights from Las Vegas Raiders vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (27, 'https://craigslist.org/semper/sapien/a/libero/nam/dui.aspx', 'Highlights from Tampa Bay Buccaneers vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (28, 'https://i2i.jp/in/purus/eu/magna/vulputate/luctus.json', 'Highlights from Arizona Cardinals vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (29, 'https://purevolume.com/neque/sapien/placerat/ante/nulla.json', 'Highlights from Dallas Cowboys vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (30, 'https://dot.gov/maecenas/tristique.xml', 'Highlights from Tennessee Titans vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (31, 'https://unicef.org/odio/cras/mi.xml', 'Highlights from Baltimore Ravens vs. Kansas City Chiefs');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (32, 'http://icq.com/quis/orci/eget/orci/vehicula/condimentum.png', 'Highlights from Green Bay Packers vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (33, 'http://bloglovin.com/ante/nulla/justo.png', 'Highlights from Carolina Panthers vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (34, 'https://noaa.gov/condimentum.json', 'Highlights from Atlanta Falcons vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (35, 'https://ifeng.com/integer/non/velit/donec/diam.aspx', 'Highlights from Buffalo Bills vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (36, 'https://walmart.com/tempus/vivamus/in/felis/eu/sapien.png', 'Highlights from Cleveland Browns vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (37, 'http://google.ru/enim/in/tempor/turpis/nec/euismod.jsp', 'Highlights from Cincinnati Bengals vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (38, 'http://oakley.com/felis/fusce/posuere.jsp', 'Highlights from Tennessee Titans vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (39, 'http://dot.gov/pretium/iaculis/justo/in/hac.aspx', 'Highlights from Arizona Cardinals vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (40, 'http://aol.com/amet/consectetuer/adipiscing/elit.js', 'Highlights from Baltimore Ravens vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (41, 'https://springer.com/congue/etiam/justo/etiam/pretium/iaculis.js', 'Highlights from Los Angeles Chargers vs. Kansas City Chiefs');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (42, 'https://seesaa.net/at/nulla.html', 'Highlights from New Orleans Saints vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (43, 'http://zimbio.com/metus/sapien/ut/nunc/vestibulum/ante/ipsum.jsp', 'Highlights from Denver Broncos vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (44, 'https://youtu.be/sem/mauris.html', 'Highlights from Las Vegas Raiders vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (45, 'https://state.gov/tristique/in/tempus/sit/amet/sem/fusce.jpg', 'Highlights from Minnesota Vikings vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (46, 'http://zimbio.com/nulla/nunc/purus/phasellus/in/felis.jsp', 'Highlights from Los Angeles Rams vs. Tampa Bay Buccaneers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (47, 'https://cyberchimps.com/eros/suspendisse.aspx', 'Highlights from Green Bay Packers vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (48, 'https://house.gov/molestie.js', 'Highlights from Dallas Cowboys vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (49, 'https://surveymonkey.com/dapibus/augue.jsp', 'Highlights from Cincinnati Bengals vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (50, 'http://ebay.com/mattis/odio/donec/vitae/nisi/nam.png', 'Highlights from Washington Football Team vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (51, 'https://ehow.com/natoque/penatibus/et.html', 'Highlights from Buffalo Bills vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (52, 'http://cafepress.com/molestie/nibh/in/lectus/pellentesque/at/nulla.js', 'Highlights from Dallas Cowboys vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (53, 'https://delicious.com/imperdiet/et/commodo.html', 'Highlights from Chicago Bears vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (54, 'https://rambler.ru/vestibulum/quam/sapien/varius/ut.jpg', 'Highlights from Cleveland Browns vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (55, 'https://photobucket.com/non/quam/nec/dui/luctus.aspx', 'Highlights from Indianapolis Colts vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (56, 'http://blogspot.com/lorem/ipsum/dolor/sit/amet/consectetuer.aspx', 'Highlights from Kansas City Chiefs vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (57, 'http://wp.com/odio/consequat/varius/integer/ac.jpg', 'Highlights from New York Giants vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (58, 'http://meetup.com/faucibus/orci.jsp', 'Highlights from New York Jets vs. Tennessee Titans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (59, 'http://tinyurl.com/eros/elementum/pellentesque/quisque.xml', 'Highlights from Arizona Cardinals vs. Los Angeles Rams');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (60, 'http://prnewswire.com/luctus/et/ultrices/posuere/cubilia.aspx', 'Highlights from Seattle Seahawks vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (61, 'https://tinypic.com/posuere.js', 'Highlights from Baltimore Ravens vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (62, 'http://tripadvisor.com/nunc/proin/at/turpis.js', 'Highlights from Green Bay Packers vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (63, 'https://ehow.com/sapien/urna/pretium/nisl.js', 'Highlights from Tampa Bay Buccaneers vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (64, 'https://usatoday.com/tellus/semper/interdum/mauris/ullamcorper.jpg', 'Highlights from Los Angeles Chargers vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (65, 'http://unc.edu/quam/fringilla/rhoncus/mauris/enim/leo.json', 'Highlights from Los Angeles Rams vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (66, 'https://jugem.jp/nonummy/integer/non/velit.jsp', 'Highlights from Atlanta Falcons vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (67, 'https://storify.com/id/ligula/suspendisse/ornare.json', 'Highlights from Philadelphia Eagles vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (68, 'https://nydailynews.com/sed.html', 'Highlights from Green Bay Packers vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (69, 'http://wired.com/imperdiet/nullam/orci/pede/venenatis/non/sodales.js', 'Highlights from Pittsburgh Steelers vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (70, 'https://rediff.com/arcu/sed/augue/aliquam/erat/volutpat.xml', 'Highlights from Minnesota Vikings vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (71, 'http://toplist.cz/eget/massa/tempor.png', 'Highlights from New England Patriots vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (72, 'https://microsoft.com/nisi/vulputate/nonummy/maecenas.html', 'Highlights from Tennessee Titans vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (73, 'http://nifty.com/integer/tincidunt/ante/vel/ipsum/praesent/blandit.aspx', 'Highlights from Tampa Bay Buccaneers vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (74, 'https://linkedin.com/eget/tempus/vel.xml', 'Highlights from New Orleans Saints vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (75, 'http://surveymonkey.com/viverra/pede/ac/diam/cras/pellentesque/volutpat.aspx', 'Highlights from Chicago Bears vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (76, 'https://elegantthemes.com/nunc/viverra/dapibus.png', 'Highlights from Los Angeles Chargers vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (77, 'https://marriott.com/non/mauris/morbi/non/lectus/aliquam/sit.jpg', 'Highlights from Arizona Cardinals vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (78, 'https://usa.gov/nisl/nunc.png', 'Highlights from Dallas Cowboys vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (79, 'https://biglobe.ne.jp/et/tempus/semper/est/quam.html', 'Highlights from Buffalo Bills vs. Kansas City Chiefs');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (80, 'http://webs.com/a/pede/posuere.png', 'Highlights from Baltimore Ravens vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (81, 'http://economist.com/eu/mi/nulla.xml', 'Highlights from Tampa Bay Buccaneers vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (82, 'https://walmart.com/odio/elementum/eu/interdum/eu/tincidunt/in.json', 'Highlights from Jacksonville Jaguars vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (83, 'https://flavors.me/nam/ultrices/libero/non/mattis/pulvinar.jsp', 'Highlights from Minnesota Vikings vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (84, 'http://cyberchimps.com/sapien/arcu/sed.jpg', 'Highlights from Green Bay Packers vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (85, 'http://google.ru/vestibulum/aliquet/ultrices/erat/tortor/sollicitudin/mi.xml', 'Highlights from Cincinnati Bengals vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (86, 'https://telegraph.co.uk/pharetra/magna.jpg', 'Highlights from Indianapolis Colts vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (87, 'https://issuu.com/gravida/nisi/at/nibh.json', 'Highlights from Kansas City Chiefs vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (88, 'http://sciencedaily.com/in/eleifend/quam/a.png', 'Highlights from Los Angeles Rams vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (89, 'https://about.me/ipsum/praesent/blandit/lacinia/erat.html', 'Highlights from Baltimore Ravens vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (90, 'http://examiner.com/ut/erat/curabitur.xml', 'Highlights from Arizona Cardinals vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (91, 'https://ow.ly/libero/convallis/eget/eleifend/luctus/ultricies.jsp', 'Highlights from Dallas Cowboys vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (92, 'https://indiatimes.com/lacus/curabitur/at/ipsum/ac.xml', 'Highlights from Las Vegas Raiders vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (93, 'https://wsj.com/lacus/purus/aliquet/at/feugiat/non.aspx', 'Highlights from Pittsburgh Steelers vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (94, 'http://taobao.com/posuere/cubilia/curae/nulla/dapibus.jsp', 'Highlights from Tennessee Titans vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (95, 'https://mediafire.com/mauris/laoreet/ut.js', 'Highlights from Cleveland Browns vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (96, 'https://drupal.org/vivamus/vestibulum/sagittis.xml', 'Highlights from Atlanta Falcons vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (97, 'http://360.cn/ultrices/libero/non/mattis/pulvinar.jpg', 'Highlights from New York Giants vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (98, 'http://prnewswire.com/quis/lectus/suspendisse/potenti/in.js', 'Highlights from Cincinnati Bengals vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (99, 'http://miibeian.gov.cn/magna/at/nunc.xml', 'Highlights from Green Bay Packers vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (100, 'https://ftc.gov/pede/venenatis/non/sodales/sed/tincidunt/eu.png', 'Highlights from Tennessee Titans vs. Kansas City Chiefs');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (101, 'http://ifeng.com/ultrices/posuere/cubilia/curae/donec/pharetra.png', 'Highlights from New England Patriots vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (102, 'http://booking.com/ornare/consequat/lectus.js', 'Highlights from Los Angeles Rams vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (103, 'https://nationalgeographic.com/nisl.jsp', 'Highlights from Las Vegas Raiders vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (104, 'http://nps.gov/pretium/nisl.jsp', 'Highlights from Tampa Bay Buccaneers vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (105, 'http://xrea.com/fusce.js', 'Highlights from Arizona Cardinals vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (106, 'https://google.com.br/sed/interdum/venenatis/turpis/enim/blandit.xml', 'Highlights from Indianapolis Colts vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (107, 'https://lulu.com/sapien.js', 'Highlights from New Orleans Saints vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (108, 'http://fastcompany.com/interdum.jpg', 'Highlights from Green Bay Packers vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (109, 'https://cdc.gov/quam.html', 'Highlights from Carolina Panthers vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (110, 'https://goodreads.com/a/nibh/in/quis/justo/maecenas.aspx', 'Highlights from Buffalo Bills vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (111, 'http://cam.ac.uk/cras.json', 'Highlights from San Francisco 49ers vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (112, 'http://umn.edu/cubilia/curae.html', 'Highlights from New York Jets vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (113, 'http://topsy.com/fusce/congue/diam/id.jsp', 'Highlights from Pittsburgh Steelers vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (114, 'https://wired.com/pharetra/magna/vestibulum/aliquet/ultrices/erat.jsp', 'Highlights from Tennessee Titans vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (115, 'http://edublogs.org/curae/donec/pharetra/magna/vestibulum.html', 'Highlights from Philadelphia Eagles vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (116, 'http://elegantthemes.com/a/ipsum.aspx', 'Highlights from Los Angeles Rams vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (117, 'http://fema.gov/venenatis/tristique/fusce/congue/diam.aspx', 'Highlights from Seattle Seahawks vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (118, 'https://csmonitor.com/in/hac/habitasse/platea.png', 'Highlights from New England Patriots vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (119, 'http://china.com.cn/quis/justo.png', 'Highlights from New Orleans Saints vs. Tampa Bay Buccaneers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (120, 'https://examiner.com/amet/consectetuer/adipiscing/elit/proin.aspx', 'Highlights from Denver Broncos vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (121, 'https://123-reg.co.uk/magnis/dis/parturient/montes.json', 'Highlights from Dallas Cowboys vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (122, 'https://thetimes.co.uk/ridiculus/mus/vivamus/vestibulum/sagittis/sapien.png', 'Highlights from Kansas City Chiefs vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (123, 'https://yahoo.com/vivamus/tortor/duis/mattis.xml', 'Highlights from Indianapolis Colts vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (124, 'http://theguardian.com/donec.html', 'Highlights from Atlanta Falcons vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (125, 'http://time.com/aliquam/erat/volutpat.aspx', 'Highlights from Jacksonville Jaguars vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (126, 'https://ihg.com/ligula/suspendisse/ornare.json', 'Highlights from Denver Broncos vs. Dallas Cowboys');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (127, 'https://statcounter.com/sem/sed/sagittis/nam/congue/risus.jpg', 'Highlights from Baltimore Ravens vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (128, 'http://harvard.edu/lorem/quisque/ut/erat/curabitur.html', 'Highlights from New England Patriots vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (129, 'http://g.co/et/ultrices/posuere/cubilia/curae/duis/faucibus.json', 'Highlights from Cleveland Browns vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (130, 'http://youku.com/tellus/nisi/eu/orci/mauris/lacinia/sapien.jpg', 'Highlights from Miami Dolphins vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (131, 'https://ed.gov/curae/duis/faucibus/accumsan/odio.js', 'Highlights from New York Giants vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (132, 'https://yellowbook.com/condimentum/neque.js', 'Highlights from Los Angeles Chargers vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (133, 'http://google.pl/eros/vestibulum/ac/est/lacinia.json', 'Highlights from Arizona Cardinals vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (134, 'http://oaic.gov.au/sem.html', 'Highlights from Kansas City Chiefs vs. Green Bay Packers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (135, 'http://trellian.com/non/ligula/pellentesque/ultrices/phasellus/id/sapien.aspx', 'Highlights from Tennessee Titans vs. Los Angeles Rams');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (136, 'http://github.io/tristique/fusce/congue/diam.html', 'Highlights from Pittsburgh Steelers vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (137, 'http://wordpress.com/at/ipsum/ac/tellus.json', 'Highlights from Miami Dolphins vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (138, 'http://yahoo.com/id/mauris/vulputate/elementum/nullam.jpg', 'Highlights from Dallas Cowboys vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (139, 'https://kickstarter.com/viverra.xml', 'Highlights from Buffalo Bills vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (140, 'https://dailymail.co.uk/sollicitudin/ut/suscipit/a/feugiat/et/eros.png', 'Highlights from Pittsburgh Steelers vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (141, 'https://networkadvertising.org/consectetuer/adipiscing/elit/proin/interdum.json', 'Highlights from Tennessee Titans vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (142, 'https://auda.org.au/odio.aspx', 'Highlights from Washington Football Team vs. Tampa Bay Buccaneers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (143, 'https://163.com/dolor/vel.jsp', 'Highlights from New England Patriots vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (144, 'https://va.gov/integer/aliquet/massa.html', 'Highlights from Indianapolis Colts vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (145, 'https://nydailynews.com/amet/cursus.xml', 'Highlights from Minnesota Vikings vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (146, 'http://booking.com/ullamcorper/purus/sit/amet.html', 'Highlights from Carolina Panthers vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (147, 'http://blinklist.com/lacinia/nisi/venenatis/tristique.jsp', 'Highlights from Philadelphia Eagles vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (148, 'https://harvard.edu/pellentesque/eget/nunc/donec/quis/orci.aspx', 'Highlights from Green Bay Packers vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (149, 'https://utexas.edu/suspendisse/accumsan/tortor/quis/turpis/sed.jpg', 'Highlights from Kansas City Chiefs vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (150, 'https://independent.co.uk/donec/diam/neque/vestibulum/eget/vulputate.json', 'Highlights from San Francisco 49ers vs. Los Angeles Rams');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (151, 'http://nbcnews.com/amet/sapien/dignissim/vestibulum.html', 'Highlights from New England Patriots vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (152, 'https://home.pl/donec.aspx', 'Highlights from Indianapolis Colts vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (153, 'http://google.cn/consectetuer.json', 'Highlights from Baltimore Ravens vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (154, 'http://globo.com/dui/vel/nisl/duis/ac/nibh.jpg', 'Highlights from Houston Texans vs. Tennessee Titans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (155, 'http://nps.gov/tincidunt/nulla.png', 'Highlights from San Francisco 49ers vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (156, 'http://reverbnation.com/sem/mauris/laoreet/ut/rhoncus/aliquet/pulvinar.jpg', 'Highlights from Philadelphia Eagles vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (157, 'https://netscape.com/eget/vulputate/ut/ultrices/vel/augue/vestibulum.html', 'Highlights from Washington Football Team vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (158, 'http://examiner.com/eu/nibh.xml', 'Highlights from Cleveland Browns vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (159, 'https://weibo.com/ultrices/posuere/cubilia/curae/duis.json', 'Highlights from Minnesota Vikings vs. Green Bay Packers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (160, 'https://dropbox.com/tempus/sit/amet.jpg', 'Highlights from Miami Dolphins vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (161, 'https://feedburner.com/quis/turpis/eget/elit.json', 'Highlights from Cincinnati Bengals vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (162, 'https://mayoclinic.com/in/hac/habitasse/platea/dictumst/morbi/vestibulum.jsp', 'Highlights from Kansas City Chiefs vs. Dallas Cowboys');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (163, 'http://tinypic.com/phasellus/sit/amet/erat.jpg', 'Highlights from Arizona Cardinals vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (164, 'https://studiopress.com/lorem/integer/tincidunt/ante/vel.jpg', 'Highlights from Los Angeles Chargers vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (165, 'https://hud.gov/in/lectus.json', 'Highlights from Tampa Bay Buccaneers vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (166, 'http://fotki.com/eget/massa/tempor/convallis/nulla/neque/libero.js', 'Highlights from Chicago Bears vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (167, 'http://bandcamp.com/nisi/at.aspx', 'Highlights from Las Vegas Raiders vs. Dallas Cowboys');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (168, 'https://microsoft.com/sem/sed/sagittis.html', 'Highlights from Buffalo Bills vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (169, 'http://zdnet.com/metus.aspx', 'Highlights from Atlanta Falcons vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (170, 'http://narod.ru/turpis/integer/aliquet.xml', 'Highlights from Cincinnati Bengals vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (171, 'http://answers.com/dui/vel.aspx', 'Highlights from New York Jets vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (172, 'http://theguardian.com/suspendisse/accumsan/tortor/quis/turpis.json', 'Highlights from New York Giants vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (173, 'http://marriott.com/erat/tortor/sollicitudin/mi/sit/amet.json', 'Highlights from Miami Dolphins vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (174, 'https://technorati.com/eros/viverra/eget/congue/eget.js', 'Highlights from Tampa Bay Buccaneers vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (175, 'http://blog.com/consequat/lectus/in/est/risus/auctor.xml', 'Highlights from New England Patriots vs. Tennessee Titans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (176, 'https://weebly.com/pharetra/magna/ac.aspx', 'Highlights from Denver Broncos vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (177, 'https://dailymotion.com/volutpat/convallis.json', 'Highlights from San Francisco 49ers vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (178, 'http://yellowbook.com/risus/dapibus/augue.jsp', 'Highlights from Green Bay Packers vs. Los Angeles Rams');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (179, 'https://google.com.au/quam/pharetra/magna.html', 'Highlights from Baltimore Ravens vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (180, 'http://goo.gl/purus.js', 'Highlights from Washington Football Team vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (181, 'https://over-blog.com/metus/arcu/adipiscing/molestie/hendrerit/at/vulputate.xml', 'Highlights from Dallas Cowboys vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (182, 'http://g.co/turpis.xml', 'Highlights from Tampa Bay Buccaneers vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (183, 'http://mozilla.org/nibh/quisque.png', 'Highlights from Arizona Cardinals vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (184, 'https://virginia.edu/posuere.jpg', 'Highlights from Los Angeles Chargers vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (185, 'https://ed.gov/hendrerit/at/vulputate/vitae/nisl/aenean/lectus.aspx', 'Highlights from Detroit Lions vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (186, 'https://surveymonkey.com/et.js', 'Highlights from Philadelphia Eagles vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (187, 'http://umn.edu/a/feugiat/et/eros/vestibulum.aspx', 'Highlights from Indianapolis Colts vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (188, 'https://tamu.edu/sit.jpg', 'Highlights from Miami Dolphins vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (189, 'http://sbwire.com/sollicitudin/vitae/consectetuer.js', 'Highlights from Seattle Seahawks vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (190, 'http://mozilla.com/commodo/placerat/praesent/blandit/nam/nulla.html', 'Highlights from Washington Football Team vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (191, 'https://timesonline.co.uk/nulla/ac/enim/in/tempor/turpis.aspx', 'Highlights from Los Angeles Rams vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (192, 'https://nps.gov/imperdiet/sapien/urna/pretium/nisl/ut/volutpat.aspx', 'Highlights from Pittsburgh Steelers vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (193, 'https://opensource.org/augue/quam/sollicitudin/vitae/consectetuer.json', 'Highlights from Kansas City Chiefs vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (194, 'http://yahoo.com/vel/accumsan/tellus/nisi.xml', 'Highlights from New England Patriots vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (195, 'http://jigsy.com/eget/orci/vehicula/condimentum/curabitur.html', 'Highlights from Minnesota Vikings vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (196, 'http://si.edu/in/est.jpg', 'Highlights from Atlanta Falcons vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (197, 'http://jimdo.com/congue/etiam.jpg', 'Highlights from San Francisco 49ers vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (198, 'http://canalblog.com/elementum/in.aspx', 'Highlights from Cleveland Browns vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (199, 'http://ftc.gov/non/ligula/pellentesque/ultrices/phasellus/id.xml', 'Highlights from Dallas Cowboys vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (200, 'https://geocities.com/nulla/eget/eros.xml', 'Highlights from Seattle Seahawks vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (201, 'http://aol.com/lacus/at.jsp', 'Highlights from Tennessee Titans vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (202, 'https://nifty.com/ut/massa/quis/augue/luctus/tincidunt/nulla.xml', 'Highlights from Kansas City Chiefs vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (203, 'https://ameblo.jp/turpis/donec.html', 'Highlights from New Orleans Saints vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (204, 'https://webmd.com/mi/integer/ac/neque/duis/bibendum.html', 'Highlights from Denver Broncos vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (205, 'https://ted.com/semper/porta.html', 'Highlights from Los Angeles Chargers vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (206, 'http://patch.com/eu/massa/donec/dapibus/duis/at.xml', 'Highlights from Tampa Bay Buccaneers vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (207, 'https://github.com/hendrerit/at/vulputate/vitae/nisl/aenean.json', 'Highlights from Green Bay Packers vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (208, 'https://noaa.gov/tincidunt/ante/vel.json', 'Highlights from Los Angeles Rams vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (209, 'https://rambler.ru/justo/aliquam/quis/turpis.xml', 'Highlights from Kansas City Chiefs vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (210, 'http://icio.us/vestibulum/velit/id/pretium.aspx', 'Highlights from Indianapolis Colts vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (211, 'https://stumbleupon.com/dui/luctus/rutrum/nulla/tellus/in/sagittis.js', 'Highlights from Buffalo Bills vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (212, 'http://toplist.cz/donec/semper/sapien.aspx', 'Highlights from Detroit Lions vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (213, 'https://dedecms.com/fusce/posuere/felis/sed.xml', 'Highlights from Dallas Cowboys vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (214, 'https://blogspot.com/vitae/nisl.js', 'Highlights from Green Bay Packers vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (215, 'https://cargocollective.com/tincidunt/ante/vel/ipsum/praesent.xml', 'Highlights from Houston Texans vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (216, 'http://yelp.com/volutpat/dui/maecenas/tristique/est/et/tempus.html', 'Highlights from Miami Dolphins vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (217, 'https://reference.com/ipsum/primis/in/faucibus/orci/luctus.html', 'Highlights from Pittsburgh Steelers vs. Tennessee Titans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (218, 'http://businesswire.com/accumsan.aspx', 'Highlights from San Francisco 49ers vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (219, 'https://phpbb.com/parturient/montes/nascetur/ridiculus.json', 'Highlights from Cincinnati Bengals vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (220, 'http://arstechnica.com/ligula/vehicula/consequat.aspx', 'Highlights from New Orleans Saints vs. Tampa Bay Buccaneers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (221, 'https://cam.ac.uk/ut.html', 'Highlights from Las Vegas Raiders vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (222, 'https://bigcartel.com/eget.jsp', 'Highlights from Minnesota Vikings vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (223, 'https://reuters.com/fermentum/donec/ut/mauris.html', 'Highlights from Philadelphia Eagles vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (224, 'http://nbcnews.com/aenean/sit/amet/justo.jpg', 'Highlights from Los Angeles Rams vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (225, 'http://imageshack.us/orci/vehicula/condimentum/curabitur/in/libero/ut.jsp', 'Highlights from Tennessee Titans vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (226, 'http://webs.com/volutpat/eleifend.jpg', 'Highlights from Green Bay Packers vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (227, 'https://homestead.com/fusce/lacus.png', 'Highlights from Indianapolis Colts vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (228, 'http://marriott.com/vivamus/metus.jpg', 'Highlights from Atlanta Falcons vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (229, 'https://who.int/in/purus.jpg', 'Highlights from Buffalo Bills vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (230, 'http://squidoo.com/dui.js', 'Highlights from Tampa Bay Buccaneers vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (231, 'http://jigsy.com/eu/est/congue.png', 'Highlights from Cincinnati Bengals vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (232, 'http://canalblog.com/donec/vitae/nisi/nam/ultrices/libero.html', 'Highlights from Houston Texans vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (233, 'http://go.com/non/sodales.jpg', 'Highlights from New York Jets vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (234, 'http://prweb.com/congue/elementum/in.jpg', 'Highlights from Los Angeles Rams vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (235, 'http://samsung.com/in/sapien/iaculis/congue/vivamus/metus.jpg', 'Highlights from Philadelphia Eagles vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (236, 'https://hugedomains.com/non/quam/nec.aspx', 'Highlights from Chicago Bears vs. Seattle Seahawks');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (237, 'https://twitpic.com/suscipit/a/feugiat/et/eros.png', 'Highlights from Las Vegas Raiders vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (238, 'https://pbs.org/ligula/vehicula/consequat/morbi/a/ipsum.jpg', 'Highlights from Kansas City Chiefs vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (239, 'http://purevolume.com/primis/in/faucibus.jpg', 'Highlights from Dallas Cowboys vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (240, 'http://bigcartel.com/quis/justo/maecenas/rhoncus.jpg', 'Highlights from Miami Dolphins vs. New Orleans Saints');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (241, 'http://list-manage.com/sit.json', 'Highlights from Buffalo Bills vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (242, 'https://creativecommons.org/ac/neque/duis/bibendum/morbi.png', 'Highlights from New Orleans Saints vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (243, 'https://youtu.be/accumsan/felis/ut/at.xml', 'Highlights from Chicago Bears vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (244, 'http://odnoklassniki.ru/elit/ac/nulla/sed/vel/enim/sit.xml', 'Highlights from Cincinnati Bengals vs. Kansas City Chiefs');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (245, 'https://fema.gov/vestibulum.json', 'Highlights from Las Vegas Raiders vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (246, 'http://google.fr/bibendum/morbi/non.jpg', 'Highlights from Arizona Cardinals vs. Dallas Cowboys');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (247, 'https://booking.com/dolor.json', 'Highlights from New England Patriots vs. Jacksonville Jaguars');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (248, 'https://fotki.com/aliquet/pulvinar/sed.js', 'Highlights from Tennessee Titans vs. Miami Dolphins');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (249, 'http://pcworld.com/ac/est/lacinia/nisi/venenatis/tristique/fusce.js', 'Highlights from Tampa Bay Buccaneers vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (250, 'https://joomla.org/auctor/sed/tristique/in.json', 'Highlights from Philadelphia Eagles vs. Washington Football Team');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (251, 'https://drupal.org/tortor/id/nulla.js', 'Highlights from Los Angeles Chargers vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (252, 'http://networkadvertising.org/orci/vehicula/condimentum/curabitur/in.jsp', 'Highlights from San Francisco 49ers vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (253, 'https://ifeng.com/ullamcorper/augue/a/suscipit/nulla.jsp', 'Highlights from Seattle Seahawks vs. Detroit Lions');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (254, 'https://is.gd/orci/luctus.html', 'Highlights from Los Angeles Rams vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (255, 'http://biblegateway.com/justo/morbi/ut.jsp', 'Highlights from Green Bay Packers vs. Minnesota Vikings');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (256, 'https://deliciousdays.com/duis/consequat/dui.xml', 'Highlights from Pittsburgh Steelers vs. Cleveland Browns');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (257, 'https://wikispaces.com/magnis.json', 'Highlights from Kansas City Chiefs vs. Denver Broncos');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (258, 'https://studiopress.com/justo/etiam/pretium/iaculis/justo.json', 'Highlights from Dallas Cowboys vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (259, 'https://etsy.com/et/magnis/dis.html', 'Highlights from New Orleans Saints vs. Atlanta Falcons');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (260, 'https://tiny.cc/ut/nunc/vestibulum/ante/ipsum/primis.jpg', 'Highlights from Tampa Bay Buccaneers vs. Carolina Panthers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (261, 'http://virginia.edu/vitae.js', 'Highlights from Minnesota Vikings vs. Chicago Bears');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (262, 'http://themeforest.net/magnis/dis/parturient/montes.html', 'Highlights from Cleveland Browns vs. Cincinnati Bengals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (263, 'http://devhub.com/viverra/eget/congue/eget.aspx', 'Highlights from Jacksonville Jaguars vs. Indianapolis Colts');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (264, 'http://wisc.edu/mi/integer/ac/neque/duis/bibendum/morbi.html', 'Highlights from Detroit Lions vs. Green Bay Packers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (265, 'https://toplist.cz/et/magnis/dis/parturient/montes/nascetur/ridiculus.xml', 'Highlights from Tennessee Titans vs. Houston Texans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (266, 'http://youtube.com/ligula/nec/sem/duis/aliquam/convallis/nunc.aspx', 'Highlights from Miami Dolphins vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (267, 'http://wix.com/in/congue/etiam/justo.aspx', 'Highlights from Washington Football Team vs. New York Giants');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (268, 'https://myspace.com/vivamus/vestibulum/sagittis/sapien/cum/sociis.jsp', 'Highlights from Pittsburgh Steelers vs. Baltimore Ravens');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (269, 'https://geocities.com/aliquam/lacus/morbi.js', 'Highlights from Buffalo Bills vs. New York Jets');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (270, 'http://themeforest.net/luctus/cum/sociis/natoque/penatibus/et.js', 'Highlights from Seattle Seahawks vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (271, 'http://baidu.com/mattis/pulvinar/nulla/pede/ullamcorper.png', 'Highlights from San Francisco 49ers vs. Los Angeles Rams');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (272, 'https://instagram.com/dui/luctus/rutrum/nulla/tellus/in/sagittis.xml', 'Highlights from Las Vegas Raiders vs. Los Angeles Chargers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (273, 'http://umn.edu/vivamus/metus.jsp', 'Highlights from Cincinnati Bengals vs. Las Vegas Raiders');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (274, 'http://prlog.org/condimentum/curabitur.html', 'Highlights from Buffalo Bills vs. New England Patriots');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (275, 'http://edublogs.org/mattis/pulvinar/nulla/pede/ullamcorper/augue/a.jsp', 'Highlights from Tampa Bay Buccaneers vs. Philadelphia Eagles');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (276, 'https://archive.org/ultricies/eu/nibh.jpg', 'Highlights from San Francisco 49ers vs. Dallas Cowboys');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (277, 'https://dedecms.com/velit/vivamus/vel/nulla/eget/eros/elementum.aspx', 'Highlights from Kansas City Chiefs vs. Pittsburgh Steelers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (278, 'http://fastcompany.com/amet.aspx', 'Highlights from Los Angeles Rams vs. Arizona Cardinals');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (279, 'http://xing.com/metus.js', 'Highlights from Cincinnati Bengals vs. Tennessee Titans');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (280, 'https://ftc.gov/elementum/ligula.html', 'Highlights from San Francisco 49ers vs. Green Bay Packers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (281, 'http://ftc.gov/massa/quis/augue/luctus/tincidunt/nulla.html', 'Highlights from Los Angeles Rams vs. Tampa Bay Buccaneers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (282, 'http://rakuten.co.jp/donec/odio/justo/sollicitudin/ut/suscipit/a.png', 'Highlights from Kansas City Chiefs vs. Buffalo Bills');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (283, 'http://people.com.cn/convallis/nulla/neque/libero/convallis/eget/eleifend.json', 'Highlights from Cincinnati Bengals vs. Kansas City Chiefs');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (284, 'http://tripod.com/velit/eu/est/congue/elementum/in.png', 'Highlights from Los Angeles Rams vs. San Francisco 49ers');
INSERT INTO 'Game_Highlight' ('game_id', 'link', 'description') VALUES (285, 'http://intel.com/vel.jsp', 'Highlights from Los Angeles Rams vs. Cincinnati Bengals');