INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (1,'CeeDee Lamb makes a catch for a gain of 78 yards','04:26',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (1,'Tom Brady scrambles for a gain of 38 yards','14:02',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (1,'Cade Otton makes a catch for a gain of 45 yards','13:33',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (1,'Giovani Bernard rushes for a gain of 74 yards','01:37',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (1,'T.Y. Hilton makes a catch for a gain of 35 yards','03:47',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (2,'Parker Hesse makes a catch for a gain of 87 yards','06:36',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (2,'Zach Pascal makes a catch for a loss of 5 yards','13:52',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (2,'Boston Scott rushes for a gain of 40 yards','01:50',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (2,'Zach Pascal makes a catch for a gain of 33 yards','06:45',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (2,'Kyle Pitts makes a catch for a gain of 42 yards','01:06',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (3,'Isaiah Hodgins makes a catch for a gain of 14 yards','14:20',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (3,'Quintin Morris makes a catch for a gain of 69 yards','11:03',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (3,'Josh Allen scrambles for a gain of 31 yards','04:16',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (3,'Dawson Knox makes a catch for a gain of 37 yards','02:19',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (3,'Kenny Pickett scrambles for a gain of 12 yards','11:58',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (4,'Tommy Tremble makes a catch for a gain of 5 yards','14:44',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (4,'James Robinson rushes for a gain of 41 yards','13:37',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (4,'Garrett Wilson makes a catch for a gain of 85 yards','00:13',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (4,'Corey Davis makes a catch for a gain of 16 yards','07:30',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (4,'Ian Thomas makes a catch for a loss of 4 yards','09:37',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (5,'JaMarr Chase makes a catch for a gain of 35 yards','03:13',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (5,'Samaje Perine rushes for a gain of 70 yards','06:07',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (5,'Kirk Cousins throws a pass for a gain of 47 yards','07:54',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (5,'Alexander Mattison rushes for a gain of 20 yards','13:52',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (5,'Hayden Hurst makes a catch for a gain of 3 yards','01:28',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (6,'Zack Moss rushes for a gain of 9 yards','14:05',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (6,'Marquise Goodwin makes a catch for a gain of 10 yards','01:35',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (6,'Godwin Igwebuike rushes for a gain of 72 yards','06:13',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (6,'Michael Dickson plays for a gain of 61 yards','09:08',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (6,'Geno Smith throws a pass for a gain of 41 yards','05:45',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (7,'Geoff Swaim makes a catch for a gain of 88 yards','02:48',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (7,'Malik Willis throws a pass for a loss of 3 yards','12:08',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (7,'Trey McBride makes a catch for a gain of 11 yards','06:38',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (7,'Corey Clement rushes for a gain of 83 yards','00:03',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (7,'Rondale Moore makes a catch for a gain of 70 yards','01:10',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (8,'James Mitchell makes a catch for a gain of 28 yards','12:49',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (8,'DJ Chark makes a catch for a gain of 69 yards','09:10',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (8,'Deebo Samuel makes a catch for a gain of 9 yards','14:13',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (8,'Shane Zylstra makes a catch for a gain of 48 yards','09:09',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (8,'Jordan Mason rushes for a gain of 36 yards','04:13',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (9,'James Robinson rushes for a gain of 3 yards','05:53',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (9,'Jamal Agnew makes a catch for a gain of 30 yards','07:53',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (9,'Evan Engram makes a catch for a gain of 53 yards','07:51',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (9,'Troy Hairston plays for a gain of 3 yards','10:38',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (9,'Marvin Jones makes a catch for a loss of 10 yards','00:13',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (10,'Larry Rountree rushes for a gain of 31 yards','01:35',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (10,'DeAndre Carter makes a catch for a gain of 16 yards','05:35',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (10,'Dax Milne makes a catch for a gain of 10 yards','04:38',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (10,'Sony Michel rushes for a gain of 9 yards','00:04',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (10,'Austin Ekeler rushes for a gain of 33 yards','13:10',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (11,'Jerick McKinnon rushes for a gain of 18 yards','13:48',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (11,'Demetric Felton rushes for a gain of 24 yards','07:01',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (11,'Jacoby Brissett scrambles for a gain of 84 yards','06:52',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (11,'Jerick McKinnon rushes for a gain of 47 yards','06:45',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (11,'Noah Gray makes a catch for a touchdown','04:17',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (12,'Brandon Johnson makes a catch for a gain of 32 yards','13:47',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (12,'Brett Rypien throws a pass for a gain of 35 yards','10:53',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (12,'Darius Slayton makes a catch for a gain of 54 yards','09:55',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (12,'Lawrence Cager makes a catch for a gain of 51 yards','01:58',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (12,'Chris Myarick plays for a loss of 4 yards','00:45',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (13,'Romeo Doubs makes a catch for a gain of 5 yards','07:01',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (13,'Juwann Winfree makes a catch for a gain of 7 yards','12:22',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (13,'Randall Cobb makes a catch for a loss of 7 yards','14:29',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (13,'Christian Watson makes a catch for a gain of 21 yards','04:57',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (13,'Nick Vannett makes a catch for a gain of 3 yards','08:49',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (14,'Marcus Jones plays for a gain of 27 yards','00:51',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (14,'Salvon Ahmed rushes for a gain of 51 yards','09:33',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (14,'Trent Sherfield makes a catch for a gain of 25 yards','04:26',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (14,'Pierre Strong rushes for a loss of 3 yards','00:21',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (14,'DeVante Parker makes a catch for a gain of 27 yards','04:43',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (15,'Brandon Powell makes a catch for a gain of 19 yards','01:15',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (15,'Lance McCutcheon makes a catch for a gain of 16 yards','06:26',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (15,'Austin Trammell makes a catch for a loss of 9 yards','06:46',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (15,'Equanimeous St. Brown makes a catch for a gain of 8 yards','05:34',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (15,'Cam Akers rushes for a gain of 77 yards','10:33',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (15,'Lance McCutcheon makes a catch for a gain of 69 yards','05:58',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (16,'Kenyan Drake rushes for a gain of 82 yards','09:21',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (16,'Brandon Bolden rushes for a gain of 1 yards','06:34',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (16,'Josh Oliver makes a catch for a loss of 3 yards','03:12',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (17,'Sterling Shepard makes a catch for a gain of 76 yards','04:21',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (17,'David Sills makes a catch for a gain of 5 yards','10:18',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (17,'Sam Howell scrambles for a gain of 68 yards','06:33',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (17,'Carson Wentz scrambles for a gain of 77 yards','10:47',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (17,'Antonio Gibson rushes for a loss of 6 yards','01:26',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (18,'Khalil Shakir makes a catch for a gain of 30 yards','01:15',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (18,'Jamison Crowder makes a catch for a loss of 7 yards','09:02',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (18,'Salvon Ahmed rushes for a gain of 77 yards','13:31',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (18,'James Cook rushes for a gain of 3 yards','10:07',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (18,'Tanner Conner makes a catch for a gain of 55 yards','05:26',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (19,'TreQuan Smith makes a catch for a gain of 12 yards','10:03',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (19,'Stephen Sullivan makes a catch for a gain of 29 yards','14:19',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (19,'Jordan Howard rushes for a loss of 7 yards','12:13',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (19,'Dwayne Washington rushes for a gain of 44 yards','01:32',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (19,'Mark Ingram rushes for a loss of 2 yards','02:34',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (20,'Darrynton Evans rushes for a loss of 10 yards','14:49',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (20,'Dante Pettis makes a catch for a gain of 56 yards','08:10',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (20,'Trayveon Williams rushes for a loss of 6 yards','01:00',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (20,'Tee Higgins makes a catch for a gain of 21 yards','11:52',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (20,'Tyler Boyd makes a catch for a gain of 58 yards','02:34',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (21,'O.J. Howard makes a catch for a gain of 30 yards','10:28',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (21,'Jack Conklin plays for a gain of 13 yards','03:31',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (21,'Troy Hairston plays for a gain of 11 yards','02:35',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (21,'Troy Hairston plays for a gain of 85 yards','00:07',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (21,'Chris Conley makes a catch for a gain of 67 yards','00:21',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (22,'Van Jefferson makes a catch for a gain of 5 yards','08:54',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (22,'Baker Mayfield scrambles for a gain of 79 yards','09:04',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (22,'Jake Gervase plays for a touchdown','12:55',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (22,'Nick Foles throws a pass for a touchdown','04:27',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (22,'Jordan Wilkins rushes for a gain of 90 yards','07:43',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (23,'Eric Saubert makes a catch for a gain of 52 yards','13:51',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (23,'James Robinson rushes for a loss of 10 yards','05:25',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (23,'Jamycal Hasty rushes for a loss of 4 yards','10:47',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (23,'C.J. Beathard throws a pass for a gain of 16 yards','03:15',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (23,'Latavius Murray rushes for a gain of 43 yards','12:51',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (24,'Zach Wilson throws a pass for a gain of 73 yards','12:20',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (24,'Tyquan Thornton makes a catch for a gain of 51 yards','10:41',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (24,'C.J. Uzomah makes a catch for a gain of 64 yards','07:40',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (24,'Ty Montgomery makes a catch for a gain of 27 yards','01:40',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (24,'Lawrence Cager makes a catch for a gain of 89 yards','01:32',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (25,'Josh Johnson throws a pass for a gain of 75 yards','00:31',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (25,'Josh Johnson throws a pass for a gain of 48 yards','04:00',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (25,'Jimmy Garoppolo scrambles for a gain of 30 yards','13:49',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (25,'Charlie Woerner makes a catch for a gain of 8 yards','01:28',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (25,'Jordan Mason rushes for a gain of 27 yards','06:44',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (26,'Jesper Horsted makes a catch for a gain of 6 yards','13:43',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (26,'Mack Hollins makes a catch for a gain of 32 yards','03:28',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (26,'Darren Waller makes a catch for a gain of 46 yards','12:07',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (26,'Pat Freiermuth makes a catch for a gain of 16 yards','12:21',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (26,'Cody White makes a catch for a gain of 78 yards','03:04',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (27,'Anthony Firkser makes a catch for a gain of 8 yards','12:49',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (27,'KeShawn Vaughn rushes for a gain of 85 yards','14:04',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (27,'Scott Miller makes a catch for a gain of 90 yards','12:20',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (27,'Feleipe Franks makes a catch for a loss of 2 yards','10:16',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (27,'Kyle Rudolph makes a catch for a gain of 30 yards','01:32',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (28,'Tyson Williams rushes for a gain of 69 yards','08:38',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (28,'Ty Chandler rushes for a gain of 90 yards','00:34',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (28,'David Blough scrambles for a gain of 10 yards','01:28',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (28,'Rondale Moore makes a catch for a gain of 47 yards','09:10',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (28,'Trace McSorley scrambles for a gain of 52 yards','05:40',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (29,'Peyton Hendershot makes a catch for a gain of 30 yards','01:00',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (29,'Bryan Anger plays for a gain of 81 yards','06:29',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (29,'Donald Parham makes a catch for a touchdown','06:26',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (29,'Jalen Guyton makes a catch for a loss of 3 yards','13:44',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (29,'Jake Ferguson makes a catch for a loss of 2 yards','10:38',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (30,'Treylon Burks makes a catch for a gain of 63 yards','02:53',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (30,'D.K. Metcalf makes a catch for a gain of 20 yards','12:40',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (30,'Chigoziem Okonkwo makes a catch for a gain of 8 yards','12:26',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (30,'Nick Westbrook-Ikhine makes a catch for a gain of 61 yards','14:36',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (30,'Ryan Tannehill throws a pass for a gain of 31 yards','04:42',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (31,'Mecole Hardman makes a catch for a gain of 57 yards','11:20',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (31,'Rashod Bateman makes a catch for a gain of 26 yards','08:42',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (31,'Tylan Wallace makes a catch for a loss of 4 yards','05:39',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (31,'JuJu Smith-Schuster makes a catch for a gain of 70 yards','01:18',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (31,'Jody Fortson makes a catch for a loss of 10 yards','14:48',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (32,'Jason Cabinda plays for a loss of 4 yards','12:35',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (32,'Tom Kennedy makes a catch for a gain of 67 yards','14:01',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (32,'Sammy Watkins makes a catch for a loss of 9 yards','14:48',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (32,'Jamaal Williams rushes for a gain of 51 yards','14:04',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (32,'Jason Cabinda plays for a gain of 65 yards','04:54',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (33,'Teagan Quitoriano makes a catch for a gain of 83 yards','08:48',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (33,'Dameon Pierce rushes for a gain of 44 yards','08:23',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (33,'Donta Foreman rushes for a gain of 23 yards','14:51',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (33,'Brevin Jordan makes a catch for a gain of 41 yards','04:45',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (33,'Rex Burkhead rushes for a gain of 85 yards','06:09',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (34,'Nick Vannett makes a catch for a gain of 26 yards','00:08',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (34,'Richie James makes a catch for a gain of 41 yards','08:45',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (34,'Drake London makes a catch for a loss of 10 yards','13:10',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (34,'KhaDarel Hodge makes a catch for a gain of 19 yards','13:24',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (34,'MyCole Pruitt makes a catch for a gain of 36 yards','01:00',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (35,'Curtis Samuel makes a catch for a gain of 66 yards','11:28',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (35,'Curtis Samuel makes a catch for a touchdown','08:55',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (35,'Cole Beasley makes a catch for a gain of 34 yards','11:26',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (35,'Terry McLaurin makes a catch for a gain of 70 yards','01:14',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (35,'Terry McLaurin makes a catch for a gain of 30 yards','07:14',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (36,'Justin Fields scrambles for a gain of 72 yards','06:37',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (36,'Deshaun Watson scrambles for a gain of 83 yards','14:57',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (36,'Daylen Baldwin makes a catch for a loss of 7 yards','04:46',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (36,'Velus Jones Jr. makes a catch for a gain of 4 yards','07:05',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (36,'Trevon Wesco makes a catch for a gain of 9 yards','02:52',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (37,'Gunner Olszewski makes a catch for a gain of 22 yards','02:42',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (37,'Jaylen Warren rushes for a gain of 49 yards','09:04',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (37,'Jaylen Warren rushes for a loss of 5 yards','02:44',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (37,'Chris Evans rushes for a gain of 77 yards','02:07',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (37,'Connor Heyward makes a catch for a gain of 32 yards','12:35',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (38,'Julius Chestnut rushes for a gain of 63 yards','13:47',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (38,'Jelani Woods makes a catch for a gain of 82 yards','14:59',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (38,'Julius Chestnut rushes for a gain of 54 yards','07:21',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (38,'Kylen Granson makes a catch for a gain of 3 yards','02:39',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (38,'Geoff Swaim makes a catch for a gain of 19 yards','10:52',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (39,'Kyler Murray scrambles for a gain of 54 yards','10:23',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (39,'Christian Kirk makes a catch for a gain of 40 yards','12:33',4);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (39,'Chris Manhertz makes a catch for a gain of 66 yards','05:30',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (39,'David Blough scrambles for a gain of 40 yards','14:47',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (39,'Travis Etienne rushes for a gain of 13 yards','06:38',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (40,'James Mitchell makes a catch for a touchdown','05:37',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (40,'Charlie Kolar makes a catch for a gain of 55 yards','11:14',1);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (40,'Craig Reynolds rushes for a loss of 10 yards','12:40',3);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (40,'Quintez Cephus makes a catch for a gain of 89 yards','02:37',2);														
INSERT INTO Play_by_Play (game_id, play_summary, time, quarter) VALUES (40,'Shane Zylstra makes a catch for a loss of 7 yards','02:43',2);														