INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (426,'Concussion','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (536,'Muscle Tear','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (537,'Hamstring Strain','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (164,'Back Injury','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (346,'Fractured Bone','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (161,'Hamstring Strain','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (5,'Torn ACL','out for Season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (529,'Concussion','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (137,'Concussion','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (385,'Shoulder Injury','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (340,'Knee Injury','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (220,'Muscle Tear','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (611,'Concussion','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (361,'Muscle Tear','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (431,'Groin Strain','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (374,'Back Injury','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (354,'Groin Strain','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (359,'Groin Strain','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (333,'Shoulder Injury','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (422,'Groin Strain','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (6,'Muscle Tear','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (62,'Knee Injury','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (147,'Fractured Bone','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (418,'Concussion','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (496,'Knee Injury','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (21,'Muscle Tear','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (224,'Hamstring Strain','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (280,'Ankle Sprain','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (239,'Muscle Tear','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (606,'Back Injury','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (356,'Groin Strain','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (474,'Groin Strain','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (297,'Fractured Bone','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (500,'Muscle Tear','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (270,'Torn ACL','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (424,'Shoulder Injury','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (258,'Ankle Sprain','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (38,'Groin Strain','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (86,'Muscle Tear','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (324,'Back Injury','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (596,'Muscle Tear','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (420,'Fractured Bone','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (396,'Shoulder Injury','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (217,'Muscle Tear','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (399,'Ankle Sprain','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (221,'Groin Strain','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (103,'Concussion','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (441,'Torn ACL','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (171,'Hamstring Strain','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (371,'Torn ACL','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (615,'Muscle Tear','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (248,'Shoulder Injury','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (436,'Back Injury','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (564,'Concussion','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (435,'Concussion','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (469,'Groin Strain','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (81,'Shoulder Injury','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (613,'Groin Strain','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (84,'Groin Strain','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (197,'Fractured Bone','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (275,'Groin Strain','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (470,'Hamstring Strain','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (622,'Fractured Bone','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (7,'Knee Injury','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (446,'Shoulder Injury','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (294,'Shoulder Injury','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (320,'Torn ACL','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (179,'Knee Injury','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (120,'Torn ACL','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (284,'Knee Injury','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (553,'Hamstring Strain','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (517,'Knee Injury','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (77,'Fractured Bone','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (449,'Back Injury','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (568,'Groin Strain','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (534,'Hamstring Strain','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (473,'Fractured Bone','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (264,'Back Injury','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (22,'Groin Strain','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (51,'Knee Injury','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (190,'Fractured Bone','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (369,'Torn ACL','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (397,'Muscle Tear','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (550,'Muscle Tear','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (358,'Concussion','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (623,'Concussion','6 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (235,'Knee Injury','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (106,'Concussion','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (61,'Groin Strain','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (592,'Hamstring Strain','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (115,'Muscle Tear','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (477,'Muscle Tear','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (107,'Torn ACL','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (492,'Ankle Sprain','2 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (372,'Fractured Bone','1 week');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (249,'Fractured Bone','5 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (183,'Torn ACL','3 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (223,'Groin Strain','4 weeks');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (575,'Back Injury','out for season');
INSERT INTO Player_Injuries (player_id, injury, duration) VALUES (569,'Torn ACL','4 weeks');